### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by byrnedo** [bencawkwell/dockerfile-dwarffortress#1] opened 2015-01-22 11:43 UTC
`Building df...
 ---> 3e09053df658
Step 1 : MAINTAINER Ben Cawkwell bencawkwell@gmail.com
 ---> Using cache
 ---> e15a102e39b5
Step 2 : RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
 ---> Using cache
 ---> e0c68c6c40fa
Step 3 : RUN apt-get update
 ---> Using cache
 ---> ebcd0523e03f
Step 4 : RUN apt-get upgrade -y
 ---> Using cache
 ---> 3da1ba480a81
Step 5 : RUN apt-get install -y supervisor
 ---> Running in ae2b45f161e2
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 supervisor : Depends: python (>= 2.3) but it is not going to be installed
              Depends: python-medusa (>= 0.5.4) but it is not going to be installed
              Depends: python-meld3 but it is not going to be installed
              Depends: python-pkg-resources (>= 0.6c7) but it is not going to be installed
              Depends: python-support (>= 0.90.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Service 'df' failed to build: The command [/bin/sh -c apt-get install -y supervisor] returned a non-zero code: 100`

**Comment by bencawkwell** [comment] 2015-01-24 06:51
Thanks for reporting the issue. I tried reproducing the issue using the command:

```
docker build --no-cache -t df -rm .
```

The package supervisor was installed without problems, and the whole docker file was built without problems. I tested most of the commands from the README to check xpra still worked etc, as far as seeing the main menu in df. This was tested using Docker version 1.1.2, build d84a070.

Please try again using the --no-cache option, and if you are still getting problems let me know what version of docker you are using, and the command you are using to build.

**Comment by byrnedo** [comment] 2015-01-24 08:20
Hi Ben,

I'm building with docker 1.3.2 and actually I used fig (www.fig.sh) to do
the build part. I got it to build in the end by changing the redirect in
the line which changes the /etc/apt/sources.list to append ( '>>' instead
of '>' ).

Could well just have been something with no-cache as well, I'll have a go
building it today maybe and see if using no-cache helps!

**Comment by bencawkwell** [comment] 2015-01-24 11:43
By changing that line, you essentially rebuilt without using the cache, since that line sits at the top of the Dockerfile. The actual change you made should make little difference, as the way it currently behaves is to remove  precise-updates and precise-security as sources.

Since you say it successfully built after you changed that line, I am going to close this issue since it was most likely caused by having an old cache of "apt-get update" that prevented installing supervisor. If I start to see this impact more people I might add "apt-get update" before each "apt-get install" command to reduce the chance of it happening, but that will make the built even slower than it is today so I would rather wait for proof that it is a common problem before changing it.

Feel free to report another issue if you get any more problems. I cannot promise I will have time to help right away but I will try.

**Closed as completed by bencawkwell** 2015-01-24 11:43 UTC
Labels: wontfix, glitch

**Comment by byrnedo** [comment] 2015-01-24 11:51
Sound, that was probably it, I have a lot of stale ubuntu builds on the
machine I did this on.
